export const SAMPLE_AI_DATA = [
  {
    name: 'Test',
    address: '20 testing street',
    city: 'New York',
    state: 'NY',
    country: 'USA',
    postal_code: '1111',
    payment_method: 'AMEX, Mastercard, Visa',
    phone: '(111) 111-1111',
    rating: 1.0,
    michelin_score: 1,
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut congue elementum mi et sagittis. Integer elementum tempor ultrices. Praesent hendrerit sodales ipsum ac hendrerit.',
    delivery_method: '',
    letter_grade: 'A',
    email: 'info@test.com',
    reservation_required: true,
    reservation_available: true,
    website: 'https://www.testing-site.com/',
    food_category: ['category1', 'category2'],
    business_hours: {
      Monday: '17:00-22:00',
      Tuesday: '17:00-22:00',
      Wednesday: '17:00-22:00',
      Thursday: '17:00-22:00',
      Friday: '17:00-23:00',
      Saturday: '17:00-23:00',
      Sunday: 'Closed',
    },
    holidays_closed: ['Thanksgiving Day', 'Christmas Day', "New Year's Day"],
    tasting_menu_only: true,
    tasting_menu_price: 550,
    price_range: '$$$$',
    drink_pairing_price: 200,
  },
];
